# .github/release.yml

changelog:
  exclude:
    labels:
      - duplicate
    authors:
      - Danaclocs
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Dropped
      labels:
        - invalid
        - wontfix
    - title: Other Changes
      labels:
        - "*"
