blank_issues_enabled: true
contact_links:
  - name: Software Engineering Project A Discussions
    url: https://github.com/kanbanyte/sepa/discussions
    about: "Please make a Discussion, Issues can be created from Discussions."
